# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 728561548d6c61db723937e8fbf073f3a53da5e8bd68508a9652add26551cf11957ef2e70df401ddd79a1260faff43dcba9bd3f9d0e59a3f6c3cfe0ea6c2a445
  user: elena
  password: esposito

test:
  secret_key_base: 4dac4ca9d24d5b7637ee31cca540ad1f5a9cb7412f04e43a168112d1bbdcbb6f6c84329fbbb0bad593f62a425716e32082b43a4ca4206cd906ca1ef4bf5f4557
  user: elena
  password: esposito

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user: elena
  password: esposito
